[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
board_build.partitions = /Users/adriandobre/.platformio/packages/framework-arduinoespressif32/tools/partitions/zigbee.csv
build_flags = -DZIGBEE_MODE_ED
